# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana:5.5.1
COPY ./config /usr/share/kibana/config
EXPOSE 5601

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
